#!/bin/sh

echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT

echo "detekt check is success"

./gradlew testDebugUnitTest
if [ $? -ne 0 ]; then
  echo "Unit tests failed, push aborted."
  exit 1
fi
echo "Unit tests passed"

echo "Running screenshot validation..."
./gradlew app:validateDebugScreenshotTest
if [ $? -ne 0 ]; then
  echo "Screenshot tests failed, push aborted."
  exit 1
fi
echo "Screenshot tests passed"

echo "All tests passed, proceeding with push."