#!/usr/bin/env bash
echo "Running spotless check..."
OUTPUT="/tmp/spotless-$(date +%s)"
./gradlew spotlessCheck > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                spotless failed                "
  echo "   Run './gradlew spotlessApply' to fix it     "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT

echo "spotless check is success"

echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT

echo "detekt check is success"
